{
 "title": "New dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "qmgr",
    "label": "QueueManager",
    "query": "from(bucket: \"gilles\")\n  |> range(start: -2y)\n  |> group(columns: [\"QueueManager\"])\n  |> distinct(column: \"QueueManager\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "queue",
    "label": "QueueName",
    "query": "from(bucket: \"gilles\")\n  |> range(start: -2y)\n  |> filter(fn: (r) => r[\"QueueManager\"] =~ /^$qmgr$/)\n  |> group(columns: [\"QueueName\"])\n  |> distinct(column: \"QueueName\")\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Put ",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "qmgr = \"${qmgr}\"\nqueue = \"${queue}\"\n\nfrom(bucket: \"gilles\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MQ Statistics\")\n  |> filter(fn: (r) => r[\"QueueManager\"] == qmgr)\n  |> filter(fn: (r) => r[\"_field\"] == \"put_count_0\" or r[\"_field\"] == \"put_count_1\")\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Put Selection",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "qmgr = \"${qmgr}\"\nqueue = \"${queue}\"\n\nfrom(bucket: \"gilles\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MQ Statistics\")\n  |> filter(fn: (r) => r[\"QueueManager\"] == qmgr)\n  |> filter(fn: (r) => r[\"QueueName\"] == queue)\n  |> filter(fn: (r) => r[\"_field\"] == \"put_count_0\" or r[\"_field\"] == \"put_count_1\")\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Get Selection",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "qmgr = \"${qmgr}\"\nqueue = \"${queue}\"\n\nfrom(bucket: \"gilles\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"MQ Statistics\")\n  |> filter(fn: (r) => r[\"QueueManager\"] == qmgr)\n  |> filter(fn: (r) => r[\"QueueName\"] == queue)\n  |> filter(fn: (r) => r[\"_field\"] == \"get_count_0\" or r[\"_field\"] == \"get_count_1\")\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}